travis:
  secure:
    BINSTAR_TOKEN: sVahbmpGHrHsSWVkOC37nKZSghbuUdVH/ZubYsAy/NEYo8FXF2/OVOmGn/p0ujV/bHnghkJZJkYdZX8IvM5WID20Uq+VxZSgyHHiTDYcVNNXrsYfBGMMcdov8SvbkLKjjh0c9RG0jKV9hugempo90M2xPivvbDCzPRLDy2w7lj4z+GxZOkbt3PgR/5jPNNEC8KSDYuwqTN4lf/G3erebAUIyp/S7gWIQuOIi4YbEj9/l7sCctIpmWy7LpVNuhMvjBsYcMrH+UQb/AWK9b9vkpf9sKEyxKzX0tl7f3+23ib4/lXtGnHbc5KbTkGwtEbIM6NItgdpqK/pXjapI9Jgzdyjd9xxOW67EvHP8w72KqCbI71Gvg555SimM3z9NOwoO6qmD7W76FsFXINUQmsrV6NUEzUIafa5DdzkT8Bkx2KQbp2I9mzv7TT0b/gzbMvvyh1hJ+ZcJgBW/TLfbDf8p5w5ELt+tqdl2QApBfLaNt3zyM0mMAsCA4KV844xaR5tsT6CCciYY8ORv+XUUvSzFYjO4a7/ZqUCyzUOkCzoX01gbhq0wbIRNnseB9QqsrRrYeiE5wkqnwMtSx56oLE++Af3tm+NuVTbw6v+bxEkxVCApHpJ5UnxmdepIhdt6S/RY/Fw7J2BxXD9nr//CfjYf3An0iQCH7IXUCElsWNKumHk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
